### ISSUE TITLE
GAuthenticator开启后，后台没有样式

### ISSUE THREAD

**Issue by M69W** [weicno/typecho-Authenticator#1]
php 7.2
数据库忘记是什么版本了
后台没报错(开启debug也没有)，但是后台没有样式了

**Comment by naicfeng** [comment]
啥叫后台样式没有了，是link的CSS没有了？截个图看看，或者发后台的html看看

**Comment by M69W** [comment]
![20181126004300](https://user-images.githubusercontent.com/15809201/48981756-b732cd80-f114-11e8-837f-045f39aa5fe4.png)
![20181126004603](https://user-images.githubusercontent.com/15809201/48981758-bb5eeb00-f114-11e8-8046-b3e7f78334b4.png)



之前的版本(0.0.1)没有问题

**Comment by M69W** [comment]
或者能否说下，我该怎么定位问题？谢谢

**Comment by naicfeng** [comment]
额，你是覆盖安装的吗？
0.0.1升级0.0.2+应该是需要卸载重新安装

**Comment by M69W** [comment]
禁用，然后开启0.0.4版本的显示 【500 Server Error】

**Comment by M69W** [comment]
![20181126005320](https://user-images.githubusercontent.com/15809201/48981860-b8182f00-f115-11e8-80b4-b1097d139625.png)

**Comment by naicfeng** [comment]
开调试看下是哪里出错
根目录下的
```
config.inc.php
```
适当位置加上
```
define('__TYPECHO_DEBUG__',true);
```

**Comment by M69W** [comment]
看到报错日志了
![20181126005617](https://user-images.githubusercontent.com/15809201/48981909-442a5680-f116-11e8-8765-b4ec98094f56.png)

**Comment by naicfeng** [comment]
有BUG，我尝试修复，先不要用吧。
但是你这个显示又不同，可能是TP开发版本修改了内容

**Comment by naicfeng** [comment]
你现在出现的问题是后台整个没法访问了吗？

**Comment by M69W** [comment]
今天刚从typecho Github上 `git clone` 最新更新
`chown -R www.www /xxxx/xx/wwwroot/`
`find /xxx/xx/wwwroot/ -type d -exec chmod 755 {} \;`
`find /xxx//xx/wwwroot/ -type f -exec chmod 644 {} \;`

**Comment by M69W** [comment]
功能正常使用，暂时就发现样式没法加载，其他的没有仔细排查

**Comment by naicfeng** [comment]
已修复，试一下，卸载重新安装

**Comment by M69W** [comment]
测试已经没问题，有个小小的建议：生成二维码那里看到是调用外部链接生成的，能不否内置，还是考虑生成引用的库大才放弃而采用外部链接生成？
例如：
https://larsjung.de/jquery-qrcode/ && https://github.com/lrsjng/jquery-qrcode
phpqcode类库 https://github.com/hehaibao/php-qrcode

最后，这个插件不错，谢谢

**Comment by naicfeng** [comment]
感觉是没必要，因为生成二维码不是核心功能，装一次插件一般就只用得上一次

**Comment by xqin** [comment]
感觉有必要, 毕竟 `Token` 需要保密, 使用那个外站生成二维码,等于把自己要保密的 `token` 变相的告知了那个网站, 而且请求的时候是有`referer`的, 那么根据日志, 那个 `http://qr.liantu.com/api.php` 的站点就可以知道你的网站是什么,然后你GA验证的 token 是什么..

**Comment by xqin** [comment]
所以还是希望下个版本 `0.0.6` 能把生成二维码的改成内置的, 或者使用jQuery的 qrcode 插件, 让js来生成二维码.

**Comment by xqin** [comment]
https://github.com/naicfeng/typecho-Authenticator/pull/2
已提PR @naicfeng  考虑一下? 我目前已经使用上改动后的代码, QRCode的展示效果与原来一致.

**Comment by naicfeng** [comment]
@xqin ok

**Comment by M69W** [comment]
终于看到这个问题更新，
下次更新即可，不用改代码了。
感谢
