### ISSUE TITLE
php 8 下无法正常重定向，显示调用非静态方法

### ISSUE THREAD

**Issue by bbsweb** [weicno/typecho-Authenticator#3]
Typecho 版本：最新 master 分支

php8 版本输入二次验证后无法正常重定向，显示：Non-static method Typecho_Response::redirect() cannot be called statically

## 解决方法
（先获取实例再调用实例方法）
将 `Action.php` 中的
```php
Typecho_Response::redirect($referer);
```
改为
```php
$response = Typecho_Response::getInstance();
$response->redirect($referer);
```

**Comment by M69W** [comment]
原来是这样，也遇到一样的问题

**Comment by naicfeng** [comment]
fix 7697d9e
