### ISSUE TITLE
Typecho 1.2.0 启用本插件，登录提示错误

### ISSUE THREAD

**Issue by clangcn** [weicno/typecho-Authenticator#4]
PHP 7.3.23
MySQL 5.7.30
nginx 1.18.0
Typecho 版本 1.2.0
启用登录验证，在输入验证码后有下面的提示：

```
Call to undefined method 
Typecho\Response::redirect()
```

盼修复！

**Comment by clangcn** [comment]
PHP 7.3.23
MySQL 5.7.30
nginx 1.18.0

**Comment by naicfeng** [comment]
https://cuojue.org/read/Typecho_Google_Authenticator_02.html

后期应该不会继续维护了。我放弃所有权利。各位大佬可以自由开发，自由分发~

**Comment by clangcn** [comment]
完了，不会弄这个啊

**Comment by vndroid** [comment]
> 完了，不会弄这个啊

我尝试修复了一下，你可以试试 https://github.com/Vndroid/GAuthenticator
